In [1]:
import pandas as pd
import numpy as np
import math

In [3]:
def performance(TP, TN, FP, FN):
    
    N = TP+TN+FP+FN
    
    Sensitivity=(TP/(TP+FN))*100

    Specificity=(1-FP/(TN+FP))*100

    Accuracy=((TP+TN)/(TP+TN+FP+FN))*100

    PPV= (TP/(TP+FP))*100 

    NPV= (TN/(TN+FN))*100 
    
    result = {
        'Sensitivity': [Sensitivity],
        'Specificity': [Specificity],
        'Accuracy':[Accuracy],
        'PPV':[PPV],
        'NPV':[NPV]
    }
    
    result_2 = pd.DataFrame(result)
    
    return result_2

In [18]:
df = pd.read_csv('C:/Users/Owner/Downloads/all_normal_EWMA_predict.csv')
df.head()

,update_time,heart_rate1,event1,pred_y1,heart_rate10,event10,pred_y10,heart_rate100,event100,pred_y100,...,pred_y996,heart_rate997,event997,pred_y997,heart_rate998,event998,pred_y998,heart_rate999,event999,pred_y999
0,08OCT23:00:00:00,73,0,0,83,0,0,88,0,0,...,0,82,0,0,80,0,0,75,0,0
1,08OCT23:00:10:00,83,0,0,81,0,0,86,0,0,...,0,91,0,0,78,0,0,91,0,0
2,08OCT23:00:20:00,90,0,0,81,0,0,59,1,0,...,0,83,0,0,63,0,0,66,0,0
3,08OCT23:00:30:00,81,0,0,65,0,0,85,0,0,...,0,72,0,0,76,0,0,85,0,0
4,08OCT23:00:40:00,96,0,0,77,0,0,74,0,0,...,0,83,0,0,86,0,0,87,0,0

In [24]:
pd.DataFrame(performance(TP=tp, TN=tn, FP=fp, FN=fn), index=['resuly1'])

         Sensitivity  Specificity  Accuracy  PPV  NPV
resuly1          NaN          NaN       NaN  NaN  NaN

In [19]:
tp = len(df[(df['event1']==1)&(df['pred_y1']==1)])
tn = len(df[(df['event1']==0)&(df['pred_y1']==0)])
fn = len(df[(df['event1']==1)&(df['pred_y1']==0)])
fp = len(df[(df['event1']==0)&(df['pred_y1']==1)])


pd.DataFrame(performance(TP=tp, TN=tn, FP=fp, FN=fn), index=['resuly1'])

# result = pd.concat([result, result_i])
# print(tp,tn,fn,fp)
# print(result_i)

         Sensitivity  Specificity  Accuracy  PPV  NPV
resuly1          NaN          NaN       NaN  NaN  NaN

In [34]:
ewma_result = pd.DataFrame()

for i in range(1,1001):

    TP = len(df[(df[f'event{i}']==1)&(df[f'pred_y{i}']==1)])
    TN = len(df[(df[f'event{i}']==0)&(df[f'pred_y{i}']==0)])
    FN = len(df[(df[f'event{i}']==1)&(df[f'pred_y{i}']==0)])
    FP = len(df[(df[f'event{i}']==0)&(df[f'pred_y{i}']==1)])


    result_i = performance(TP=TP, TN=TN, FP=FP, FN=FN)
    
    ewma_result = pd.concat([ewma_result, result_i])
    
ewma_result.index = [f"result{i}" for i in range(1, 1001)]

ewma_result.head(2)

         Sensitivity  Specificity   Accuracy        PPV        NPV
result1    15.384615    98.480243  95.321637  28.571429  96.716418
result2    18.750000    96.625767  92.982456  21.428571  96.036585

In [38]:
mean_ewma = pd.DataFrame(index=['mean'])

mean_ewma['mean_sens'] = ewma_result['Sensitivity'].mean()
mean_ewma['mean_spec'] = ewma_result['Specificity'].mean()
mean_ewma['mean_accu'] = ewma_result['Accuracy'].mean()
mean_ewma['mean_ppv'] = ewma_result['PPV'].mean()
mean_ewma['mean_npv'] = ewma_result['NPV'].mean()

mean_ewma

      mean_sens  mean_spec  mean_accu  mean_ppv  mean_npv
mean  28.515873  98.078949  95.232456  37.95214  96.98838